# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and Publish Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.oss}}
    strategy:
     matrix:
      oss: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml --update-snapshots verify
      
  publish:
      runs-on: windows-latest
      needs: build
      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'oracle'
            java-version: '17'
        - name: Build with Maven and skip Test Steps
          run: mvn --batch-mode --update-snapshots package -DskipTest
        - name: Create a directory and copy Artifacts
          run: mkdir temp && cp target/*.jar temp
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: Package
            path: temp
    
    
  
